# syntax = docker/dockerfile:1

# Use a specific Node.js version suitable for your project
FROM node:22

# Set the working directory
WORKDIR /app

# Copy only package.json and package-lock.json first for dependency installation
COPY package*.json ./
COPY prisma/ ./

# Install dependencies
RUN npm install

# Copy the rest of the project files
COPY . .

# Expose the development server port
EXPOSE 3000

# Set default command
CMD ["npm", "run", "dev"]
