// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIRunRequest api run request
//
// swagger:model apiRunRequest
type APIRunRequest struct {

	// j
	J string `json:"j,omitempty"`

	// o
	O []string `json:"o"`

	// q
	Q string `json:"q,omitempty"`
}

// Validate validates this api run request
func (m *APIRunRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIRunRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIRunRequest) UnmarshalBinary(b []byte) error {
	var res APIRunRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
