// Code generated by go-swagger; DO NOT EDIT.

package j_q_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/jingweno/jqplay/api/swagger/models"
)

// NewJQServicePostRunParams creates a new JQServicePostRunParams object
// with the default values initialized.
func NewJQServicePostRunParams() *JQServicePostRunParams {
	var ()
	return &JQServicePostRunParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewJQServicePostRunParamsWithTimeout creates a new JQServicePostRunParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewJQServicePostRunParamsWithTimeout(timeout time.Duration) *JQServicePostRunParams {
	var ()
	return &JQServicePostRunParams{

		timeout: timeout,
	}
}

// NewJQServicePostRunParamsWithContext creates a new JQServicePostRunParams object
// with the default values initialized, and the ability to set a context for a request
func NewJQServicePostRunParamsWithContext(ctx context.Context) *JQServicePostRunParams {
	var ()
	return &JQServicePostRunParams{

		Context: ctx,
	}
}

// NewJQServicePostRunParamsWithHTTPClient creates a new JQServicePostRunParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewJQServicePostRunParamsWithHTTPClient(client *http.Client) *JQServicePostRunParams {
	var ()
	return &JQServicePostRunParams{
		HTTPClient: client,
	}
}

/*JQServicePostRunParams contains all the parameters to send to the API endpoint
for the j q service post run operation typically these are written to a http.Request
*/
type JQServicePostRunParams struct {

	/*Body*/
	Body *models.APIRunRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the j q service post run params
func (o *JQServicePostRunParams) WithTimeout(timeout time.Duration) *JQServicePostRunParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the j q service post run params
func (o *JQServicePostRunParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the j q service post run params
func (o *JQServicePostRunParams) WithContext(ctx context.Context) *JQServicePostRunParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the j q service post run params
func (o *JQServicePostRunParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the j q service post run params
func (o *JQServicePostRunParams) WithHTTPClient(client *http.Client) *JQServicePostRunParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the j q service post run params
func (o *JQServicePostRunParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the j q service post run params
func (o *JQServicePostRunParams) WithBody(body *models.APIRunRequest) *JQServicePostRunParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the j q service post run params
func (o *JQServicePostRunParams) SetBody(body *models.APIRunRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *JQServicePostRunParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
