// Code generated by go-swagger; DO NOT EDIT.

package j_q_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jingweno/jqplay/api/swagger/models"
)

// JQServicePostRunReader is a Reader for the JQServicePostRun structure.
type JQServicePostRunReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *JQServicePostRunReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewJQServicePostRunOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewJQServicePostRunDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewJQServicePostRunOK creates a JQServicePostRunOK with default headers values
func NewJQServicePostRunOK() *JQServicePostRunOK {
	return &JQServicePostRunOK{}
}

/*JQServicePostRunOK handles this case with default header values.

A successful response.
*/
type JQServicePostRunOK struct {
	Payload *models.APIRunResponse
}

func (o *JQServicePostRunOK) Error() string {
	return fmt.Sprintf("[POST /run][%d] jQServicePostRunOK  %+v", 200, o.Payload)
}

func (o *JQServicePostRunOK) GetPayload() *models.APIRunResponse {
	return o.Payload
}

func (o *JQServicePostRunOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIRunResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewJQServicePostRunDefault creates a JQServicePostRunDefault with default headers values
func NewJQServicePostRunDefault(code int) *JQServicePostRunDefault {
	return &JQServicePostRunDefault{
		_statusCode: code,
	}
}

/*JQServicePostRunDefault handles this case with default header values.

An unexpected error response.
*/
type JQServicePostRunDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the j q service post run default response
func (o *JQServicePostRunDefault) Code() int {
	return o._statusCode
}

func (o *JQServicePostRunDefault) Error() string {
	return fmt.Sprintf("[POST /run][%d] JQService_PostRun default  %+v", o._statusCode, o.Payload)
}

func (o *JQServicePostRunDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *JQServicePostRunDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
