// Code generated by go-swagger; DO NOT EDIT.

package j_q_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new j q service API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for j q service API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	JQServicePostRun(params *JQServicePostRunParams) (*JQServicePostRunOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  JQServicePostRun j q service post run API
*/
func (a *Client) JQServicePostRun(params *JQServicePostRunParams) (*JQServicePostRunOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewJQServicePostRunParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "JQService_PostRun",
		Method:             "POST",
		PathPattern:        "/run",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &JQServicePostRunReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*JQServicePostRunOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*JQServicePostRunDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
