// Code generated by go-swagger; DO NOT EDIT.

package j_q_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/jingweno/jqplay/api/swagger/models"
)

// NewPostRunParams creates a new PostRunParams object
// with the default values initialized.
func NewPostRunParams() *PostRunParams {
	var ()
	return &PostRunParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostRunParamsWithTimeout creates a new PostRunParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostRunParamsWithTimeout(timeout time.Duration) *PostRunParams {
	var ()
	return &PostRunParams{

		timeout: timeout,
	}
}

// NewPostRunParamsWithContext creates a new PostRunParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostRunParamsWithContext(ctx context.Context) *PostRunParams {
	var ()
	return &PostRunParams{

		Context: ctx,
	}
}

// NewPostRunParamsWithHTTPClient creates a new PostRunParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostRunParamsWithHTTPClient(client *http.Client) *PostRunParams {
	var ()
	return &PostRunParams{
		HTTPClient: client,
	}
}

/*PostRunParams contains all the parameters to send to the API endpoint
for the post run operation typically these are written to a http.Request
*/
type PostRunParams struct {

	/*Body*/
	Body *models.APIRunRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post run params
func (o *PostRunParams) WithTimeout(timeout time.Duration) *PostRunParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post run params
func (o *PostRunParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post run params
func (o *PostRunParams) WithContext(ctx context.Context) *PostRunParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post run params
func (o *PostRunParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post run params
func (o *PostRunParams) WithHTTPClient(client *http.Client) *PostRunParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post run params
func (o *PostRunParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post run params
func (o *PostRunParams) WithBody(body *models.APIRunRequest) *PostRunParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post run params
func (o *PostRunParams) SetBody(body *models.APIRunRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostRunParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
